# Use this file to list funding links for the project (GitHub Sponsors, Open Collective, etc.)
# For more information see: https://docs.github.com/en/repositories/managing-your-repository/displaying-a-sponsor-button-in-your-repository

# Replace or remove entries below as desired.
contact: sany2k8dev@gmail.com
